

services:
  postgres:
    image: postgres:15
    container_name: raya_postgres
    environment:
      POSTGRES_DB: raya_db
      POSTGRES_USER: raya_user
      POSTGRES_PASSWORD: raya_password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
